package com.nhapp.data.model

import kotlinx.serialization.Serializable
import java.util.UUID

@Serializable
data class Profile(
    val id: String, // UUID
    val name: String?,
    val email: String? = null,
    val avatar_url: String?,
    val fcm_token: String? = null,
    val created_at: String
)

@Serializable
data class Chat(
    val id: String? = null, // UUID, generated by DB
    val created_at: String? = null, // Generated by DB
    val created_by: String? = null
)

@Serializable
data class ChatMember(
    val chat_id: String,
    val user_id: String
)

@Serializable
data class Message(
    val id: String? = null, // UUID, generated by DB
    val chat_id: String,
    val sender_id: String,
    val content: String,
    val image_url: String? = null,
    val created_at: String? = null, // Generated by DB
    val read_at: String? = null
)

data class ChatWithProfile(
    val chat: Chat,
    val partnerProfile: Profile?
)
